### ISSUE TITLE
ExpressionList can match trailing commas

### ISSUE THREAD

**Issue by AmaranthineCodices** [LPGhatguy/lua-parser#7]
This is a departure from Lua syntax, where a trailing comma in an expression list is a parse error:

```lua
print(1, 2,)
```

`ParseExpressionList` does not handle this right now; it will parse a trailing comma perfectly fine.

**Comment by LPGhatguy** [comment]
Oops.

Free feature!

I really want to turn these into macro combinators instead of writing all of these functions for zero or more and one or more lists of things.

**Comment by AmaranthineCodices** [comment]
Got fixed in 4f0f7ef3eb49ca1921f09ba9db61545465d33039, I believe.
